//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGrp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGrp() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceGrp", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 管理區列表 的當地語系化字串。
        /// </summary>
        internal static string btnList {
            get {
                return ResourceManager.GetString("btnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新結果 的當地語系化字串。
        /// </summary>
        internal static string btnResult {
            get {
                return ResourceManager.GetString("btnResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳送指令 的當地語系化字串。
        /// </summary>
        internal static string btnSendCmd {
            get {
                return ResourceManager.GetString("btnSendCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組設定 的當地語系化字串。
        /// </summary>
        internal static string btnSetting {
            get {
                return ResourceManager.GetString("btnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        internal static string btnSetting2 {
            get {
                return ResourceManager.GetString("btnSetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建築物名稱 的當地語系化字串。
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設值 的當地語系化字串。
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備英文名稱 的當地語系化字串。
        /// </summary>
        internal static string EquEName {
            get {
                return ResourceManager.GetString("EquEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備群組描述 的當地語系化字串。
        /// </summary>
        internal static string EquGrpDesc {
            get {
                return ResourceManager.GetString("EquGrpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備群組名稱 的當地語系化字串。
        /// </summary>
        internal static string EquGrpName {
            get {
                return ResourceManager.GetString("EquGrpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備群組編號 的當地語系化字串。
        /// </summary>
        internal static string EquGrpNo {
            get {
                return ResourceManager.GetString("EquGrpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備型號 的當地語系化字串。
        /// </summary>
        internal static string EquModel {
            get {
                return ResourceManager.GetString("EquModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備名稱 的當地語系化字串。
        /// </summary>
        internal static string EquName {
            get {
                return ResourceManager.GetString("EquName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備編號 的當地語系化字串。
        /// </summary>
        internal static string EquNo {
            get {
                return ResourceManager.GetString("EquNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備類型 的當地語系化字串。
        /// </summary>
        internal static string EquType {
            get {
                return ResourceManager.GetString("EquType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門禁設備 的當地語系化字串。
        /// </summary>
        internal static string EquTypeDA {
            get {
                return ResourceManager.GetString("EquTypeDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電梯設備 的當地語系化字串。
        /// </summary>
        internal static string EquTypeElev {
            get {
                return ResourceManager.GetString("EquTypeElev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 餐勤設備 的當地語系化字串。
        /// </summary>
        internal static string EquTypeMeal {
            get {
                return ResourceManager.GetString("EquTypeMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 考勤設備 的當地語系化字串。
        /// </summary>
        internal static string EquTypeTRT {
            get {
                return ResourceManager.GetString("EquTypeTRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入方式 的當地語系化字串。
        /// </summary>
        internal static string InputMode {
            get {
                return ResourceManager.GetString("InputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 樓層名稱 的當地語系化字串。
        /// </summary>
        internal static string lblFloorName {
            get {
                return ResourceManager.GetString("lblFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理區列表 的當地語系化字串。
        /// </summary>
        internal static string lblMgnAreaList {
            get {
                return ResourceManager.GetString("lblMgnAreaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此列表僅供參考，無法進行編輯 的當地語系化字串。
        /// </summary>
        internal static string propReadOnly {
            get {
                return ResourceManager.GetString("propReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回應設備資訊 的當地語系化字串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規則 的當地語系化字串。
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備群組 的當地語系化字串。
        /// </summary>
        internal static string ttEquGroup {
            get {
                return ResourceManager.GetString("ttEquGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已加入 的當地語系化字串。
        /// </summary>
        internal static string ttJoin {
            get {
                return ResourceManager.GetString("ttJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所屬管理區列表 的當地語系化字串。
        /// </summary>
        internal static string ttMgnAreaList {
            get {
                return ResourceManager.GetString("ttMgnAreaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待加入 的當地語系化字串。
        /// </summary>
        internal static string ttUnJoin {
            get {
                return ResourceManager.GetString("ttUnJoin", resourceCulture);
            }
        }
    }
}
