//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahoAcs.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SahoAcs.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增連線裝置 的當地語系化字串。
        /// </summary>
        public static string AddConn {
            get {
                return ResourceManager.GetString("AddConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增控制器 的當地語系化字串。
        /// </summary>
        public static string AddCtrl {
            get {
                return ResourceManager.GetString("AddCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增設備 的當地語系化字串。
        /// </summary>
        public static string AddEqu {
            get {
                return ResourceManager.GetString("AddEqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增讀卡機 的當地語系化字串。
        /// </summary>
        public static string AddReader {
            get {
                return ResourceManager.GetString("AddReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動回傳 的當地語系化字串。
        /// </summary>
        public static string AutoReturn {
            get {
                return ResourceManager.GetString("AutoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新     增 的當地語系化字串。
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進階查詢 的當地語系化字串。
        /// </summary>
        public static string btnAdvance {
            get {
                return ResourceManager.GetString("btnAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理區列表 的當地語系化字串。
        /// </summary>
        public static string btnAuth {
            get {
                return ResourceManager.GetString("btnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取權限資料 的當地語系化字串。
        /// </summary>
        public static string btnAuthData {
            get {
                return ResourceManager.GetString("btnAuthData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備群組設定 的當地語系化字串。
        /// </summary>
        public static string btnAuthEquGroup {
            get {
                return ResourceManager.GetString("btnAuthEquGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取     消 的當地語系化字串。
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清     除 的當地語系化字串。
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪     除 的當地語系化字串。
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編     輯 的當地語系化字串。
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備列表 的當地語系化字串。
        /// </summary>
        public static string btnEquList {
            get {
                return ResourceManager.GetString("btnEquList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開 的當地語系化字串。
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出 的當地語系化字串。
        /// </summary>
        public static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入 的當地語系化字串。
        /// </summary>
        public static string btnJoin {
            get {
                return ResourceManager.GetString("btnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 左移 的當地語系化字串。
        /// </summary>
        public static string btnLeft {
            get {
                return ResourceManager.GetString("btnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登     入 的當地語系化字串。
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確　 定 的當地語系化字串。
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查     詢 的當地語系化字串。
        /// </summary>
        public static string btnQuery {
            get {
                return ResourceManager.GetString("btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新傳送 的當地語系化字串。
        /// </summary>
        public static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移除 的當地語系化字串。
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 右移 的當地語系化字串。
        /// </summary>
        public static string btnRight {
            get {
                return ResourceManager.GetString("btnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲     存 的當地語系化字串。
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢     視 的當地語系化字串。
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單機設碼 的當地語系化字串。
        /// </summary>
        public static string CodeSetting {
            get {
                return ResourceManager.GetString("CodeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線模式 的當地語系化字串。
        /// </summary>
        public static string ConnMode {
            get {
                return ResourceManager.GetString("ConnMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線類型 的當地語系化字串。
        /// </summary>
        public static string ConnType {
            get {
                return ResourceManager.GetString("ConnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器說明 的當地語系化字串。
        /// </summary>
        public static string CtrlInfo {
            get {
                return ResourceManager.GetString("CtrlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器機型 的當地語系化字串。
        /// </summary>
        public static string CtrlModel {
            get {
                return ResourceManager.GetString("CtrlModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器名稱 的當地語系化字串。
        /// </summary>
        public static string CtrlName {
            get {
                return ResourceManager.GetString("CtrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器編號 的當地語系化字串。
        /// </summary>
        public static string CtrlNo {
            get {
                return ResourceManager.GetString("CtrlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器介面 的當地語系化字串。
        /// </summary>
        public static string CtrlSet {
            get {
                return ResourceManager.GetString("CtrlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器狀態 的當地語系化字串。
        /// </summary>
        public static string CtrlStatus {
            get {
                return ResourceManager.GetString("CtrlStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string ddlDefault {
            get {
                return ResourceManager.GetString("ddlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取資料 的當地語系化字串。
        /// </summary>
        public static string ddlSelectDefault {
            get {
                return ResourceManager.GetString("ddlSelectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線裝置介面 的當地語系化字串。
        /// </summary>
        public static string DeviceConnSet {
            get {
                return ResourceManager.GetString("DeviceConnSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線裝置說明 的當地語系化字串。
        /// </summary>
        public static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線裝置 的當地語系化字串。
        /// </summary>
        public static string DeviceIP {
            get {
                return ResourceManager.GetString("DeviceIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線裝置機型 的當地語系化字串。
        /// </summary>
        public static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線裝置編號 的當地語系化字串。
        /// </summary>
        public static string DeviceNo {
            get {
                return ResourceManager.GetString("DeviceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未啟用 的當地語系化字串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對應設備 的當地語系化字串。
        /// </summary>
        public static string EquMap {
            get {
                return ResourceManager.GetString("EquMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備名稱 的當地語系化字串。
        /// </summary>
        public static string EquName {
            get {
                return ResourceManager.GetString("EquName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備編號 的當地語系化字串。
        /// </summary>
        public static string EquNo {
            get {
                return ResourceManager.GetString("EquNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選 的當地語系化字串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 韌體版本 的當地語系化字串。
        /// </summary>
        public static string FirmVer {
            get {
                return ResourceManager.GetString("FirmVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 樓層 的當地語系化字串。
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進 的當地語系化字串。
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進入管制區 的當地語系化字串。
        /// </summary>
        public static string InMgn {
            get {
                return ResourceManager.GetString("InMgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 方向控制 的當地語系化字串。
        /// </summary>
        public static string InOut {
            get {
                return ResourceManager.GetString("InOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備權限列表 的當地語系化字串。
        /// </summary>
        public static string lblAuthDataList {
            get {
                return ResourceManager.GetString("lblAuthDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本系統請使用Intermet Explorer 10 或 以上版本 的當地語系化字串。
        /// </summary>
        public static string lblBrowserAlarm {
            get {
                return ResourceManager.GetString("lblBrowserAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件 的當地語系化字串。
        /// </summary>
        public static string lblCondition {
            get {
                return ResourceManager.GetString("lblCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料列表 的當地語系化字串。
        /// </summary>
        public static string lblDataList {
            get {
                return ResourceManager.GetString("lblDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        public static string lblEnd {
            get {
                return ResourceManager.GetString("lblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saho 商合行 &amp;copy;Copyright  All Rights Reserved. 的當地語系化字串。
        /// </summary>
        public static string lblFooter {
            get {
                return ResourceManager.GetString("lblFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似               總共 {0} 筆      的當地語系化字串。
        /// </summary>
        public static string lblGvCounts {
            get {
                return ResourceManager.GetString("lblGvCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已加入 的當地語系化字串。
        /// </summary>
        public static string lblJoin {
            get {
                return ResourceManager.GetString("lblJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號與密碼不得為空白!! 的當地語系化字串。
        /// </summary>
        public static string lblLoginChk {
            get {
                return ResourceManager.GetString("lblLoginChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息 的當地語系化字串。
        /// </summary>
        public static string lblMsg {
            get {
                return ResourceManager.GetString("lblMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作業類型： 的當地語系化字串。
        /// </summary>
        public static string lblProcessType {
            get {
                return ResourceManager.GetString("lblProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者密碼 的當地語系化字串。
        /// </summary>
        public static string lblPwd {
            get {
                return ResourceManager.GetString("lblPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您好!! 的當地語系化字串。
        /// </summary>
        public static string lblRegards {
            get {
                return ResourceManager.GetString("lblRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟始時間 的當地語系化字串。
        /// </summary>
        public static string lblStart {
            get {
                return ResourceManager.GetString("lblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SMS 多元管理平台 的當地語系化字串。
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 至 的當地語系化字串。
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者帳號 的當地語系化字串。
        /// </summary>
        public static string lblUid {
            get {
                return ResourceManager.GetString("lblUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未加入 的當地語系化字串。
        /// </summary>
        public static string lblUnJoin {
            get {
                return ResourceManager.GetString("lblUnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第一頁 的當地語系化字串。
        /// </summary>
        public static string lbtnFirst {
            get {
                return ResourceManager.GetString("lbtnFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最末頁 的當地語系化字串。
        /// </summary>
        public static string lbtnLast {
            get {
                return ResourceManager.GetString("lbtnLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一頁 的當地語系化字串。
        /// </summary>
        public static string lbtnNext {
            get {
                return ResourceManager.GetString("lbtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前一頁 的當地語系化字串。
        /// </summary>
        public static string lbtnPrev {
            get {
                return ResourceManager.GetString("lbtnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 機號 的當地語系化字串。
        /// </summary>
        public static string MacNo {
            get {
                return ResourceManager.GetString("MacNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MapEqu 的當地語系化字串。
        /// </summary>
        public static string MapEqu {
            get {
                return ResourceManager.GetString("MapEqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用連線 的當地語系化字串。
        /// </summary>
        public static string MasterConn {
            get {
                return ResourceManager.GetString("MasterConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料 的當地語系化字串。
        /// </summary>
        public static string NonData {
            get {
                return ResourceManager.GetString("NonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請注意!!  目前無法進行刪除\n\n可能的原因：1.沒有資料可供刪除。\n　　　　　　2.尚未選擇要刪除的項目。\n 的當地語系化字串。
        /// </summary>
        public static string NotSelectForDelete {
            get {
                return ResourceManager.GetString("NotSelectForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請注意!!  目前無法進行編輯\n\n可能的原因：1.沒有資料可供編輯。\n　　　　　　2.尚未選擇要編輯的項目。\n 的當地語系化字串。
        /// </summary>
        public static string NotSelectForEdit {
            get {
                return ResourceManager.GetString("NotSelectForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請注意!!  目前無法進行傳送查詢\n\n可能的原因：1.沒有資料可供傳送查詢。\n　　　　　　2.尚未選擇要傳送查詢的項目。\n 的當地語系化字串。
        /// </summary>
        public static string NotSelectForQuery {
            get {
                return ResourceManager.GetString("NotSelectForQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請注意!!  目前無法進行傳送設定\n\n可能的原因：1.沒有資料可供傳送。\n　　　　　　2.尚未選擇要傳送的項目。\n 的當地語系化字串。
        /// </summary>
        public static string NotSelectForSend {
            get {
                return ResourceManager.GetString("NotSelectForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出 的當地語系化字串。
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開管制區 的當地語系化字串。
        /// </summary>
        public static string OutMgn {
            get {
                return ResourceManager.GetString("OutMgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數設定 的當地語系化字串。
        /// </summary>
        public static string ParaSetting {
            get {
                return ResourceManager.GetString("ParaSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人員 的當地語系化字串。
        /// </summary>
        public static string rdoPsn {
            get {
                return ResourceManager.GetString("rdoPsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string rdoUser {
            get {
                return ResourceManager.GetString("rdoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機說明 的當地語系化字串。
        /// </summary>
        public static string ReaderInfo {
            get {
                return ResourceManager.GetString("ReaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機名稱 的當地語系化字串。
        /// </summary>
        public static string ReaderName {
            get {
                return ResourceManager.GetString("ReaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機編號 的當地語系化字串。
        /// </summary>
        public static string ReaderNo {
            get {
                return ResourceManager.GetString("ReaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀卡機介面 的當地語系化字串。
        /// </summary>
        public static string ReaderSet {
            get {
                return ResourceManager.GetString("ReaderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 限制 的當地語系化字串。
        /// </summary>
        public static string Restrict {
            get {
                return ResourceManager.GetString("Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
